apiVersion: v1
kind: Service
metadata:
  name: chronicle-service
  namespace: dsm
spec:
  selector:
    app: chronicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
