apiVersion: v1
kind: Service
metadata:
  name: sprint-service
  namespace: dsm
spec:
  selector:
    app: sprint-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
