apiVersion: v1
kind: ConfigMap
metadata:
  name: sprint-pg-hba-config
  namespace: dsm
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::/0                    md5
    host    all             all             10.244.0.0/16           md5
