apiVersion: v1
kind: Pod
metadata:
  name: test-secret-config-pod
  namespace: dsm
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo POSTGRES_DB=$POSTGRES_DB; echo POSTGRES_USER=$POSTGRES_USER; echo POSTGRES_HOST=$POSTGRES_HOST; echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD; sleep 3600"]
    env:
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: project-db-config
          key: POSTGRES_DB
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: project-db-config
          key: POSTGRES_USER
    - name: POSTGRES_HOST
      valueFrom:
        configMapKeyRef:
          name: project-db-config
          key: POSTGRES_HOST
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: project-db-secret
          key: POSTGRES_PASSWORD
  restartPolicy: Never