apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronicle-db-v17-vector
  namespace: dsm
  labels:
    app: chronicle-db-v17-vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronicle-db-v17-vector
  template:
    metadata:
      labels:
        app: chronicle-db-v17-vector
    spec:
      containers:
        - name: postgres
          image: myreg.agile-corp.org:5000/chronicle-db-pgvector:17.1
          envFrom:
            - configMapRef:
                name: postgres-chronicle-config
            - secretRef:
                name: postgres-chronicle-secret
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "600m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-chronicle-pvc-v17-vector
