apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: dsm
  labels:
    app: embedding-service
spec:
  type: ClusterIP
  selector:
    app: embedding-service
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
