apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-pv
  namespace: dsm
spec:
  storageClassName: nfs-client
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfs/k8s/gt/ollama-llm-data
    server: 10.204.32.7
  claimRef:
    name: ollama-models-pvc
    namespace: dsm
