apiVersion: v1
kind: ConfigMap
metadata:
  name: project-setup-requirements-cm
  namespace: dsm
data:
  requirements.txt: |
    psycopg2-binary==2.9.7
    structlog==23.1.0
    pandas==2.0.3
    mimesis==12.0.0
    numpy==1.24.4