apiVersion: v1
kind: ConfigMap
metadata:
  name: project-db-pg-hba-config
  namespace: dsm
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    project_db      dsm_user        0.0.0.0/0               md5