apiVersion: v1
kind: Service
metadata:
  name: test-log-app-service
  labels:
    app: test-log-app
spec:
  selector:
    app: test-log-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
