apiVersion: v1
kind: Service
metadata:
  name: project-orchestrator
  namespace: dsm
spec:
  selector:
    app: project-orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
